NIFTY_50 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK",
    "HINDUNILVR", "ITC", "SBIN", "BHARTIARTL", "KOTAKBANK",
    "LT", "AXISBANK", "ASIANPAINT", "MARUTI", "TITAN",
    "SUNPHARMA", "BAJFINANCE", "HCLTECH", "WIPRO", "ULTRACEMCO",
    "NESTLEIND", "TATAMOTORS", "NTPC", "POWERGRID", "ONGC",
    "COALINDIA", "ADANIENT", "ADANIPORTS", "TATASTEEL", "JSWSTEEL",
    "TECHM", "BAJAJFINSV", "INDUSINDBK", "HINDALCO", "DRREDDY",
    "DIVISLAB", "CIPLA", "EICHERMOT", "BPCL", "TATACONSUM",
    "GRASIM", "APOLLOHOSP", "HEROMOTOCO", "SBILIFE", "BAJAJ-AUTO",
    "BEL", "TRENT", "SHRIRAMFIN", "DLF", "LICI",
]

NIFTY_NEXT_50 = [
    "ABB", "AMBUJACEM", "ATGL", "BANKBARODA", "BERGEPAINT",
    "BOSCHLTD", "CANBK", "CHOLAFIN", "COLPAL", "CONCOR",
    "DABUR", "DMART", "GODREJCP", "HDFCAMC", "HDFCLIFE",
    "HAL", "HAVELLS", "ICICIPRULI", "IDFCFIRSTB", "INDHOTEL",
    "IOC", "IRCTC", "IRFC", "JINDALSTEL", "LICHSGFIN",
    "LUPIN", "MARICO", "MAXHEALTH", "MUTHOOTFIN", "NHPC",
    "OFSS", "PAGEIND", "PFC", "PIDILITIND",
    "PNB", "POLYCAB", "RECLTD", "SBICARD", "SIEMENS",
    "SRF", "TATAELXSI", "TATAPOWER", "TORNTPHARM", "TVSMOTOR",
    "UNIONBANK", "VEDL", "VBL", "YESBANK", "ZOMATO",
]
