NIFTY_50 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK",
    "HINDUNILVR", "ITC", "SBIN", "BHARTIARTL", "KOTAKBANK",
    "LT", "AXISBANK", "ASIANPAINT", "MARUTI", "TITAN",
    "SUNPHARMA", "BAJFINANCE", "HCLTECH", "WIPRO", "ULTRACEMCO",
    "NESTLEIND", "NTPC", "POWERGRID", "ONGC",
    "COALINDIA", "ADANIENT", "ADANIPORTS", "TATASTEEL", "JSWSTEEL",
    "TECHM", "BAJAJFINSV", "INDUSINDBK", "HINDALCO", "DRREDDY",
    "DIVISLAB", "CIPLA", "EICHERMOT", "BPCL", "TATACONSUM",
    "GRASIM", "APOLLOHOSP", "HEROMOTOCO", "SBILIFE", "BAJAJ-AUTO",
    "BEL", "TRENT", "SHRIRAMFIN", "DLF", "LICI",
]

NIFTY_NEXT_50 = [
    "ABB", "AMBUJACEM", "ATGL", "BANKBARODA", "BERGEPAINT",
    "BOSCHLTD", "CANBK", "CHOLAFIN", "COLPAL", "CONCOR",
    "DABUR", "DMART", "GODREJCP", "HDFCAMC", "HDFCLIFE",
    "HAL", "HAVELLS", "ICICIPRULI", "IDFCFIRSTB", "INDHOTEL",
    "IOC", "IRCTC", "IRFC", "JINDALSTEL", "LICHSGFIN",
    "LUPIN", "MARICO", "MAXHEALTH", "MUTHOOTFIN", "NHPC",
    "OFSS", "PAGEIND", "PFC", "PIDILITIND",
    "PNB", "POLYCAB", "RECLTD", "SBICARD", "SIEMENS",
    "SRF", "TATAELXSI", "TATAPOWER", "TORNTPHARM", "TVSMOTOR",
    "UNIONBANK", "VEDL", "VBL", "YESBANK",
]

NIFTY_MIDCAP = [
    "ABCAPITAL", "ACC", "ADANIGREEN", "ADANIPOWER", "ALKEM",
    "AUROPHARMA", "BALKRISIND", "BANDHANBNK", "BATAINDIA", "BHARATFORG",
    "BHEL", "BIOCON", "BSE", "CANFINHOME", "CGPOWER",
    "CHAMBLFERT", "COFORGE", "COROMANDEL", "CROMPTON", "CUMMINSIND",
    "DEEPAKNTR", "DEVYANI", "DIXON", "ESCORTS", "FACT",
    "FEDERALBNK", "FORTIS", "GAIL", "GLENMARK", "GMRINFRA",
    "GNFC", "GRANULES", "GUJGASLTD", "HAPPSTMNDS", "HONASA",
    "IEX", "INDUSTOWER", "JKCEMENT", "JSWENERGY", "JUBLFOOD",
    "KALYANKJIL", "KEI", "KPITTECH", "LAURUSLABS", "LTF",
    "LTTS", "M&MFIN", "MANAPPURAM", "MANKIND", "MCX",
    "METROPOLIS", "MFSL", "MGL", "MOTHERSON", "MPHASIS",
    "MRF", "NAM-INDIA", "NATIONALUM", "NAUKRI", "NAVINFLUOR",
    "NCC", "NMDC", "OBEROIRLTY", "OIL", "PAYTM",
    "PERSISTENT", "PETRONET", "PRESTIGE", "PVRINOX", "RAMCOCEM",
    "RVNL", "SAIL", "SJVN", "SOLARINDS", "SONACOMS",
    "STARHEALTH", "SUNDARMFIN", "SUNTV", "SUPREMEIND", "SYNGENE",
    "TATACHEM", "TATACOMM", "THERMAX", "TIINDIA", "TORNTPOWER",
    "UBL", "UPL", "VOLTAS", "WHIRLPOOL", "ZYDUSLIFE",
]

NIFTY_SMALLCAP = [
    "AARTIIND", "AFFLE", "AJANTPHARM", "ANGELONE", "APARINDS",
    "ASTRAL", "ATUL", "AVANTIFEED", "BASF", "BAYERCROP",
    "BDL", "BSOFT", "CAMPUS", "CARBORUNIV", "CDSL",
    "CENTURYTEX", "CESC", "CLEAN", "CMSINFO", "COCHINSHIP",
    "CUB", "CYIENT", "DCMSHRIRAM", "ELGIEQUIP", "EMAMILTD",
    "ENGINERSIN", "EQUITASBNK", "FINCABLES", "FINEORG", "FLUOROCHEM",
    "GESHIP", "GILLETTE", "GLAXO", "GRINDWELL", "GSPL",
    "HATSUN", "HINDPETRO", "HUDCO", "IDFC", "IIFL",
    "INDIACEM", "INDIANB", "IRCON", "ITI", "JBCHEPHARM",
    "JKLAKSHMI", "JMFINANCIL", "JSL", "JSWINFRA", "JUSTDIAL",
    "KALPATPOWR", "KANSAINER", "KEC", "KFINTECH", "KNRCON",
    "LALPATHLAB", "LATENTVIEW", "LAXMIMACH", "LINDEINDIA", "MAPMYINDIA",
    "MASTEK", "MCDOWELL-N", "MEDANTA", "MOTILALOFS", "MRPL",
    "NATCOPHARM", "NBCC", "NETWORK18", "NLCINDIA", "POWERINDIA",
    "PRAJIND", "RADICO", "RAJESHEXPO", "RATNAMANI", "RAYMOND",
    "REDINGTON", "RENUKA", "ROUTE", "RPOWER", "SANOFI",
    "SCHAEFFLER", "SCHNEIDER", "SFL", "SOBHA", "SPARC",
    "SUMICHEM", "SUVENPHAR", "SWSOLAR", "TANLA", "TATAINVEST",
    "TTML", "TV18BRDCST", "USHAMART", "VAIBHAVGBL", "VGUARD",
    "VINATIORGA", "VSTIND", "WELCORP", "ZEEL",
]


def get_tickers(level="nifty50"):
    if level == "nifty50":
        return NIFTY_50
    elif level == "nifty100":
        return NIFTY_50 + NIFTY_NEXT_50
    elif level == "nifty200":
        return NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP
    elif level == "full":
        return NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP + NIFTY_SMALLCAP
    return NIFTY_50


def get_scan_info():
    return {
        "nifty50": {"label": "Nifty 50", "count": len(NIFTY_50), "est_minutes": 2},
        "nifty100": {"label": "Nifty 100", "count": len(NIFTY_50 + NIFTY_NEXT_50), "est_minutes": 5},
        "nifty200": {"label": "Nifty 200+", "count": len(NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP), "est_minutes": 12},
        "full": {"label": "Full Market", "count": len(NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP + NIFTY_SMALLCAP), "est_minutes": 25},
    }
